### ISSUE TITLE
{Bug} npm run build not work

### ISSUE THREAD

**Issue by lolminerxmrig** [rockiger/reactpress#44]
hi.
plz help me for fixed Error:

[ssdasdassfdafd@host wo]$ npm run build

> wo@0.1.0 build
> PUBLIC_URL=/wp-content/reactpress/apps/wo/build react-scripts build

Creating an optimized production build...
/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

RangeError: WebAssembly.Instance(): Out of memory: wasm memory
    at create (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/webpack/lib/util/hash/wasm-hash.js:154:4)
    at module.exports (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/webpack/lib/util/createHash.js:176:6)
    at /home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/webpack/lib/DefinePlugin.js:341:22
    at Hook.eval [as call] (eval at create (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/tapable/lib/HookCodeFactory.js:1:1), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/webpack/lib/Compiler.js:1126:26)
    at /home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/webpack/lib/Compiler.js:1170:29
    at Hook.eval [as callAsync] (eval at create (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/tapable/lib/HookCodeFactory.js:1:1), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/ssdasdassfdafd/public_html/wo.ssdasdassfdafd.com/wp-content/reactpress/apps/wo/node_modules/webpack/lib/Compiler.js:1165:28)

Node.js v18.17.0

**Comment by rockiger** [comment]
This looks like a problem with a node package of your app. I don't see any connection to with ReactPress. Try to remove
```
PUBLIC_URL=/wp-content/reactpress/apps/wo/build 
```
in your `package.json`. Does it build then?
